FROM ubuntu:18.04

MAINTAINER Peter Prochnicki <piotr.prochnicki@gmail.com>

RUN apt-get update 

RUN apt-get install -y openjdk-11-jre
 
RUN apt-get install -y python3.7
 
RUN apt-get install -y phpmyadmin
 
RUN apt-get install -y net-tools
