
import java.io.Reader;
import java.net.*;
import java.awt.Color;
import java.awt.Component;
import java.awt.Container;
import java.awt.event.ActionEvent;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.io.File;
import java.io.InputStreamReader;
import java.io.FileReader;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.OutputStream;
import java.io.PrintStream;
import java.io.PrintWriter;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.GroupLayout;
import javax.swing.JButton;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
    

/**
 *
 * @author as
 */
public class Zegar extends javax.swing.JFrame implements ItemListener {
    private Container panel;
    private Component wyjscie;

    
   // static JTextField tf;
    /**
     * Creates new form Zegar
     */
    public Zegar() {
        initComponents();
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField4 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();

        jTextField4.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextField2.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jTextField3.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jTextField5.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jTextField5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tunga", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Wybierz opcje:");

        jLabel2.setFont(new java.awt.Font("Tunga", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Podaj wage:");

        jLabel3.setFont(new java.awt.Font("Tunga", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Podaj wzrost:");

        jLabel4.setFont(new java.awt.Font("Tunga", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("BMI wynosi:");

        jButton1.setText("Oblicz");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Obliczenia(evt);
            }
        });

        jButton2.setText("2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("9");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("8");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("1");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("7");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("4");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText("5");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setText("6");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "waga", "wzrost" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jButton11.setText("C");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setText("0");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                        .addComponent(jTextField5, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                        .addComponent(jTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                        .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton4))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jButton6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton2))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton9)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton3))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addComponent(jComboBox1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField5, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(jButton3)
                            .addComponent(jButton6)
                            .addComponent(jButton11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton8)
                                    .addComponent(jButton9)
                                    .addComponent(jButton10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jButton7)
                                        .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addComponent(jButton5)))
                            .addComponent(jButton12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Obliczenia(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Obliczenia
        OutputStream os = null;
    //   Wynik ramka2=new Wynik();
    //   ramka2.setVisible(true);
        try {
            // TODO add your handling code here:
            String stringA= jTextField2.getText();
            double A=Double.parseDouble(stringA);
            String stringB= jTextField3.getText();
            double B=Double.parseDouble(stringB);
            Bmi wsk=new Bmi();
            //Scanner sc=new Scanner(jTextField2.getText());
            // if(sc.equals(Color.red)==true)
            wsk.setA(A);
            // if(sc.equals(Color.pink)==true)
            wsk.setB(B);
            wsk.setwynik();
            File fp=new File("plik.txt");
            os = new FileOutputStream("plik.txt");
            PrintStream printstream= new PrintStream(os);
            printstream.print(Double.toString((Math.round(wsk.getwynik()))));
            printstream.close();
            jTextField5.setText(""+Double.toString((Math.round(wsk.getwynik()))));
/*
   final int PORT=50007;
   //tworzenie gniazda serwerowego                                        
   ServerSocket serv;                                                     
   serv=new ServerSocket(PORT);                                           
                                                                             
   //oczekiwanie na polaczenie i tworzenie gniazda sieciowego             
   System.out.println("Nasluchuje: "+serv);                               
   Socket sock;                                                           
   sock=serv.accept();                                                    
   System.out.println("Jest polaczenie: "+sock);                          
                                                                             
   //tworzenie strumienia danych pobieranych z gniazda sieciowego         
   BufferedReader inp;                                                    
   inp=new BufferedReader(new InputStreamReader(sock.getInputStream()));  
                                                                             
   //komunikacja - czytanie danych ze strumienia                          
   String str;                                                            
   str=inp.readLine();                                                    
   System.out.println("<Nadeszlo:> " + str);                              
                                                                             
   //zamykanie polaczenia                                                 
   inp.close();                                                           
   sock.close();                                                          
   serv.close(); 

      final int PORT2=50007;
      final String HOST = "127.0.0.1";
      //nawiazanie polaczenia z serwerem                                               
      Socket sock2;                                                                     
      sock2=new Socket(HOST,PORT2);                                                      
      System.out.println("Nawiazalem polaczenie: "+sock);                              
                                                                                       
      //tworzenie strumieni danych pobieranych z klawiatury i dostarczanych do socketu 
      BufferedReader klaw; 
   FileReader in = new FileReader("plik.txt");                                                             
      klaw=new BufferedReader(in);                       
      PrintWriter outp;                                                                
      outp=new PrintWriter(sock.getOutputStream());                                    
                                                                                       
      //komunikacja - czytanie danych z klawiatury i przekazywanie ich do strumienia   
      System.out.print("<Wysylamy:> ");                                                
      String str2=klaw.readLine();                                                      
      outp.println(str2);                                                               
      outp.flush();                                                                    
                                                                                       
      //zamykanie polaczenia                                                           
      klaw.close();                                                                    
      outp.close();                                                                    
      sock.close();  
*/
    
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Zegar.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Zegar.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                os.close();
            } catch (IOException ex) {
                Logger.getLogger(Zegar.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        Wynik wsk =new Wynik(); 
        
        GroupLayout layout = new GroupLayout(panel);
        panel.setLayout(layout);
        layout.setAutoCreateGaps(true);
        layout.setAutoCreateContainerGaps(true);
        layout.setHorizontalGroup(
   layout.createSequentialGroup()
      .addComponent(jTextField5)
      .addComponent(wsk.add(wyjscie))
      .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
           .addComponent(jTextField5)
           .addComponent(wsk.add(wyjscie)))
);
layout.setVerticalGroup(
   layout.createSequentialGroup()
      .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
           .addComponent(jTextField5)
           .addComponent(wsk.add(wyjscie))
           /*.addComponent(c3)*/)
      //.addComponent(c4)
);
        
    }//GEN-LAST:event_Obliczenia

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here;
       String opcja=jComboBox1.getSelectedItem().toString();
           
           if(opcja.equals("waga"))
             jTextField3.setText(jTextField3.getText()+"4");
           else if(opcja.equals("wzrost"))
             jTextField2.setText(jTextField2.getText()+"4");  
      
        
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        //jTextField3.setText(jTextField3.getText()+"6");
        
         String opcja=jComboBox1.getSelectedItem().toString();
           
           if(opcja.equals("waga"))
             jTextField3.setText(jTextField3.getText()+"6");
           else if(opcja.equals("wzrost"))
             jTextField2.setText(jTextField2.getText()+"6");  
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        //jTextField3.setText(jTextField3.getText()+"9");
        
   String opcja=jComboBox1.getSelectedItem().toString();
           
           if(opcja.equals("waga"))
             jTextField3.setText(jTextField3.getText()+"9");
           else if(opcja.equals("wzrost"))
             jTextField2.setText(jTextField2.getText()+"9");  
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
      //  jTextField3.setText(jTextField3.getText()+"8");
        
          String opcja=jComboBox1.getSelectedItem().toString();
           
           if(opcja.equals("waga"))
             jTextField3.setText(jTextField3.getText()+"8");
           else if(opcja.equals("wzrost"))
             jTextField2.setText(jTextField2.getText()+"8");  
    }//GEN-LAST:event_jButton5ActionPerformed


    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
       // jTextField3.setText(jTextField3.getText()+"1");
        
               String opcja=jComboBox1.getSelectedItem().toString();
           
           if(opcja.equals("waga"))
             jTextField3.setText(jTextField3.getText()+"1");
           else if(opcja.equals("wzrost"))
             jTextField2.setText(jTextField2.getText()+"1");  
               
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        //jTextField3.setText(jTextField3.getText()+"2");
        
              String opcja=jComboBox1.getSelectedItem().toString();
           
           if(opcja.equals("waga"))
             jTextField3.setText(jTextField3.getText()+"2");
           else if(opcja.equals("wzrost"))
             jTextField2.setText(jTextField2.getText()+"2");  
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
       // jTextField3.setText(jTextField3.getText()+"3");
        
               String opcja=jComboBox1.getSelectedItem().toString();
           
           if(opcja.equals("waga"))
             jTextField3.setText(jTextField3.getText()+"3");
           else if(opcja.equals("wzrost"))
             jTextField2.setText(jTextField2.getText()+"3");  
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        //jTextField3.setText(jTextField3.getText()+"7");
        String opcja=jComboBox1.getSelectedItem().toString();
           
           if(opcja.equals("waga"))
             jTextField3.setText(jTextField3.getText()+"7");
           else if(opcja.equals("wzrost"))
             jTextField2.setText(jTextField2.getText()+"7");  
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        //jTextField3.setText(jTextField3.getText()+"5");
        
             String opcja=jComboBox1.getSelectedItem().toString();
           
           if(opcja.equals("waga"))
             jTextField3.setText(jTextField3.getText()+"5");
           else if(opcja.equals("wzrost"))
             jTextField2.setText(jTextField2.getText()+"5");  
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
       String opcja=jComboBox1.getSelectedItem().toString();
            
       jComboBox1.addItem("waga");
       jComboBox1.addItem("wzrost");
  
       String wart9=jButton9.getSelectedIcon().toString();
       String wart7=jButton7.getSelectedIcon().toString();              
       String wart3=jButton3.getSelectedIcon().toString();
       String wart2=jButton2.getSelectedIcon().toString();
       String wart6=jButton6.getSelectedIcon().toString();
       String wart5=jButton5.getSelectedIcon().toString();
       String wart4=jButton4.getSelectedIcon().toString();
       String wart10=jButton10.getSelectedIcon().toString();
       String wart8=jButton8.getSelectedIcon().toString();
        String wart12=jButton12.getSelectedIcon().toString();
           String wart11=jButton11.getSelectedIcon().toString();
// for(int d=1;d<=9;d++)
// {
       if(opcja.equals("waga"))
       {
           if(opcja.equals("wart9")!=true){
             jTextField3.setText(jTextField3.getText()+"5");
           }
             if(opcja.equals("wart7")!=true){
             jTextField3.setText(jTextField3.getText()+"7");
               }
             if(opcja.equals("wart3")!=true){
             jTextField3.setText(jTextField3.getText()+"3");
               }
                if(opcja.equals("wart2")!=true){
              jTextField3.setText(jTextField3.getText()+"2");
               }
                if(opcja.equals("wart6")!=true){
              jTextField3.setText(jTextField3.getText()+"1");
               }
                if(opcja.equals("wart5")!=true){
              jTextField3.setText(jTextField3.getText()+"8");
               }
               if(opcja.equals("wart4")!=true){
               jTextField3.setText(jTextField3.getText()+"9");
               }
                if(opcja.equals("wart10")!=true){
               jTextField3.setText(jTextField3.getText()+"6");
               }
                if(opcja.equals("wart8")!=true){
               jTextField3.setText(jTextField3.getText()+"4");
               }
                 if(opcja.equals("wart12")!=true){
               jTextField3.setText(jTextField3.getText()+"0");
               }
                  if(opcja.equals("wart11")!=true){
                jTextField3.setBackground(Color.GREEN);
               }
           //}
           }     
           else if(opcja.equals("wzrost"))
           {
             if(opcja.equals("wart9")!=true){
             jTextField2.setText(jTextField2.getText()+"5");
           }
             if(opcja.equals("wart7")!=true){
             jTextField2.setText(jTextField2.getText()+"7");
               }
             if(opcja.equals("wart3")!=true){
             jTextField2.setText(jTextField2.getText()+"3");
               }
                if(opcja.equals("wart2")!=true){
              jTextField2.setText(jTextField2.getText()+"2");
               }
                if(opcja.equals("wart6")!=true){
              jTextField2.setText(jTextField2.getText()+"1");
               }
                if(opcja.equals("wart5")!=true){
              jTextField2.setText(jTextField2.getText()+"8");
               }
               if(opcja.equals("wart4")!=true){
               jTextField2.setText(jTextField2.getText()+"9");
               }
                if(opcja.equals("wart10")!=true){
               jTextField2.setText(jTextField2.getText()+"6");
               }
                if(opcja.equals("wart8")!=true){
               jTextField2.setText(jTextField2.getText()+"4");
               } 
                 if(opcja.equals("wart12")!=true){
               jTextField2.setText(jTextField2.getText()+"0");
               }
                  if(opcja.equals("wart11")!=true){
                jTextField2.setForeground(Color.red);
               }
           }
 //}             
            // jTextField2.setText(jTextField2.getText()+"5");  
   
           
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        String opcja=jComboBox1.getSelectedItem().toString();
           
           if(opcja.equals("waga"))
             jTextField3.setText(jTextField3.getText()+"0");
           else if(opcja.equals("wzrost"))
             jTextField2.setText(jTextField2.getText()+"0");  
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        String opcja=jComboBox1.getSelectedItem().toString();
           
           if(opcja.equals("waga")){
              jTextField3.setForeground(Color.red);
               
             /*jTextField4.setText(jTextField3.getText()+" ");  
             jTextField3.setText(jTextField2.getText()+" "); 
             jTextField2.setText(jTextField4.getText()+" ");*/
           }
             else if(opcja.equals("wzrost"))
              jTextField2.setForeground(Color.pink); 
                 
             /*jTextField4.setText(jTextField3.getText()+" ");  
             jTextField3.setText(jTextField2.getText()+" "); 
             jTextField2.setText(jTextField4.getText()+" "); */
    }//GEN-LAST:event_jButton11ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Zegar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Zegar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Zegar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Zegar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Zegar().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables

    @Override
    public void itemStateChanged(ItemEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}

